### ISSUE TITLE
可以有详细一点的配置方法嘛

### ISSUE THREAD

**Issue by RichardZhang4** [YtFlow/Maple#46]
可以有详细一点的配置方法嘛？目前的对我来说还是有点困难，不知道从哪里开始怎么弄

**Comment by RichardZhang4** [comment]
希望有客户端中文

**Comment by bdbai** [comment]
> 不知道从哪里开始怎么弄

你想实现的功能是什么？例如什么协议的代理、需不需要分流？按照 README 的说明，现在卡在哪里？

> 希望有客户端中文

中文暂时不会有。

**Comment by RichardZhang4** [comment]
> > 不知道从哪里开始怎么弄
> 
> 你想实现的功能是什么？例如什么协议的代理、需不需要分流？按照 README 的说明，现在卡在哪里？
> 
> > 希望有客户端中文
> 
> 中文暂时不会有。

就类似CFM的配置文件这种
```
proxies:
p: &p
  type: http
  interval: 3600
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
f: &f
  type: file
  behavior: classical
t: &t
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 10
  use:
    - 机场一
    - 机场二
    - 机场三
g: &g
  type: select
  proxies:
    - 机场一
    - 机场二
    - 机场三
    - 自动选择
    - PASS
    - 直连
    - 香港
    - 台湾
    - 日本
    - 新加坡
    - 美国

proxy-providers:
  
  机场一:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场1.yaml
  机场二:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场2.yaml
  机场三:
    <<: *p
    url: "订阅地址"
    path: ./proxy_providers/机场3.yaml
    
# 机场一,机场二为机场名，可以改名，如果要换名必须全换，否则启动失败

proxy-groups:
  - name: 机场
    <<: *g
  - name: 机场一
    type: select
    use:
      - 机场一
  - name: 机场二
    type: select
    use:
      - 机场二
  - name: 机场三
    type: select
    use:
      - 机场三
  
  - name: 香港
    filter: "港|香港|HK|HongKong"
    <<: *t
  - name: 台湾
    filter: "台|台湾|TW|Taiwan"
    <<: *t
  - name: 日本
    filter: "日|日本|JP|Japan"
    <<: *t
  - name: 美国
    filter: "美|美国|US|UnitedStates"
    <<: *t
  - name: 新加坡
    filter: "新|新加坡|SG|Singapore|狮城"
    <<: *t  
  - name: 自动选择
    <<: *t
  - name: 游戏
    <<: *g
  - name: 哔哩哔哩
    <<: *g
 
  - name: 广告过滤
    type: select
    proxies:
      - 拦截
      - PASS
      
  - name: 拦截
    type: select
    proxies:
      - REJECT
      
  - name: 直连
    type: select
    proxies:
      - DIRECT

  - name: 国内
    type: select
    proxies:
      - 直连
      - 机场

  - name: 其他
    type: select
    proxies:
      - 机场
      - 国内
      - DIRECT

rule-providers:  
  AppProxy:
    <<: *f
    path: ./rule_providers/AppProxy.yaml
  AppDirect:
    <<: *f
    path: ./rule_providers/AppDirect.yaml 
  userDirect:
    <<: *f
    path: ./rule_providers/userDirect.yaml 
rules:
  - RULE-SET,AppProxy,机场
  - RULE-SET,AppDirect,国内
  - RULE-SET,userDirect,国内
  - GEOSITE,category-games,游戏
  - GEOSITE,category-ads-all,广告过滤 # 去广告规则，不想用，最前面的加上#号即可
  - GEOSITE,Google,机场    
  - GEOSITE,BiliBili,哔哩哔哩
  - GEOSITE,geolocation-cn,国内
  - GEOSITE,geolocation-!cn,机场
  - GEOIP,Google,机场
  - GEOIP,CN,国内
  - GEOIP,!CN,机场
  - MATCH,其他

```
